[package]
version     = "0.5.0"
flix        = "0.76.2"
repository  = "github:stephentetley/flix-path"

[dependencies]
"github:stephentetley/effect-extras" = { version = "0.7.0", security = "unrestricted", mount = "ee" }
"github:stephentetley/adaptor-extras" = { version = "0.6.0", security = "unrestricted", mount = "ae" }
